#!/usr/bin/env python3
"""Writes ../README.md from the assets in ../assets. Dark/light twins go through <picture>; neutral SVGs are plain <img>."""
from pathlib import Path
import re
OUT = Path(__file__).resolve().parent.parent / 'README.md'
SNAKE = 'https://raw.githubusercontent.com/overloooooord/overloooooord/output/github-snake'

def alt_of(name):
    return re.search(r'aria-label="([^"]+)"', (OUT.parent / 'assets' / f'{name}.svg').read_text()).group(1)

def pic(name, width='100%', alt=None, href=None):
    alt = alt or alt_of(name)
    s = (f'<picture><source media="(prefers-color-scheme: dark)" srcset="assets/{name}.svg"><source media="(prefers-color-scheme: light)" '
         f'srcset="assets/{name}-light.svg"><img src="assets/{name}.svg" width="{width}" alt="{alt}"></picture>')
    return f'<a href="{href}">{s}</a>' if href else s

def img(name, width='100%', alt=None, href=None):
    s = f'<img src="assets/{name}.svg" width="{width}" alt="{alt or alt_of(name)}">'
    return f'<a href="{href}">{s}</a>' if href else s

FT = 'https://efes-ccl.vercel.app'
parts = [
'<!-- Akai (赤) Anime profile. Every SVG in assets/ is generated by tools/build_assets.py and tools/lab.py: all type is vector paths, so it renders the same on every OS. This file is written by tools/build_readme.py. -->',
'',
'<p align="center">',
pic('hero'),
pic('ribbon-status'),
'</p>',
'',
'<sub>PROLOGUE · 第零話</sub>',
'',
'Final years of Software Engineering at KBTU, Almaty. Three years of building Python backends that ship: Django and FastAPI services, PostgreSQL schemas, Telegram bots, browser and API automation, computer vision on OpenCV, and the Angular or React fronts that sit on top of them. In 2026 that meant a pairing engine for Efes Kazakhstan with 412 drinks in it, an AI scoring pipeline for inDrive at Decentrathon 5.0, a Telegram analytics SaaS in private beta with 703 tests behind it, and three more builds in the lab. The old bio said <code>pythoooooooooon</code>. Still accurate.',
'',
pic('chapter-01'),
'',
pic('sheet'),
'',
pic('divider'),
'',
pic('chapter-02'),
'',
'<p align="center">',
img('ft-page-champ', href='https://efesccl-champ.vercel.app'),
img('ft-page-public', href=FT),
'</p>',
'',
pic('flavor-stats'),
'',
'Sensory beer education for Efes Kazakhstan, built for OneIdea Championship 2026. Every drink is decomposed into a Top / Heart / Base flavor pyramid, the way a perfumer reads a scent. The pairing engine is explainable by design: each match returns a score, its type (complement, contrast, cleanse or bridge), three reasons in plain language, a serving temperature and a glass. Venues get QR menus, guests get an AI sommelier on Claude. Angular 18 on the front, Django REST and PostgreSQL behind it, 150+ backend tests, business plan and Lean Canvas in the repo, deployed on Vercel and Railway.',
'',
'<p>',
pic('btn-live', '32.9%', href=FT),
pic('btn-devrepo', '32.9%', href='https://github.com/overloooooord/efesccl-champ'),
pic('btn-teamrepo', '32.9%', href='https://github.com/Adelllya/Efes-ccl-Flavor'),
'</p>',
'',
'<br>',
'',
pic('chapter-03'),
'',
pic('quest-smm'),
'',
'<p>',
pic('quest-invision', '49.5%', href='https://github.com/overloooooord/indrive') + pic('quest-igtg', '49.5%'),
'</p>',
'',
'<sub>InVision U was a team of three (with Ilyas Aitkhozha and Denis): 186 commits, 49 mine. The latest commit dropped the backend from the tree, so the full source with backend and ML lives at <a href="https://github.com/overloooooord/indrive/tree/3c30480">3c30480</a>. SMM Radar is my own product and has no public repo yet. Scores in InVision U track a candidate\'s growth trajectory, not a snapshot of grades.</sub>',
'',
pic('divider'),
'',
pic('chapter-04'),
'',
pic('automation'),
'',
pic('ops'),
'',
'<sub>Three years of this before the products: pipelines that log in, verify, collect and report on their own, with a dashboard to watch them and a Telegram bot to steer them. Repos with client accounts and credentials stay private.</sub>',
'',
'<br>',
'',
pic('chapter-05'),
'',
pic('lab'),
'',
'<br>',
'',
pic('chapter-06'),
'',
pic('clients'),
'',
'<sub>Finance Bridge: <a href="https://finance-bridge-one.vercel.app">live</a> · <a href="https://github.com/Adelllya/Finance_Bridge">source</a>. SHADE: <a href="https://shade-web-five.vercel.app">live</a>. Two front ends with public links; the rest of the client work sits in private repos.</sub>',
'',
pic('divider'),
'',
pic('chapter-07'),
'',
pic('contrib-log'),
'',
'<p align="center">',
f'<picture><source media="(prefers-color-scheme: dark)" srcset="{SNAKE}-dark.svg"><source media="(prefers-color-scheme: light)" srcset="{SNAKE}.svg"><img src="{SNAKE}-dark.svg" width="100%" alt="Contribution snake eating the last year of commits"></picture>',
'</p>',
'',
'<br>',
'',
pic('chapter-next'),
'',
'<p>',
pic('katana', '50%') + pic('next-episode', '49.8%'),
'</p>',
'',
'<p>',
pic('btn-telegram', '32.9%', href='https://t.me/dreamdrainer'),
pic('btn-instagram', '32.9%', href='https://www.instagram.com/_abutalifuly_/'),
pic('btn-tiktok', '32.9%', href='https://www.tiktok.com/@machiavellistt'),
'</p>',
'',
pic('footer'),
'',
]
md = '\n'.join(parts) + '\n'
assert not re.search('[—–]', md), 'dash found'
OUT.write_text(md)
print(OUT, len(md), 'chars', md.count('<img'), 'imgs')
