#!/usr/bin/env python3
"""Writes ../README.md from the assets in ../assets. Dark/light twins go through <picture>; neutral SVGs are plain <img>."""
from pathlib import Path
import hashlib, re
OUT = Path(__file__).resolve().parent.parent / 'README.md'
LOG = 'https://raw.githubusercontent.com/overloooooord/overloooooord/output/log'   # drawn daily by tools/contrib_turtle.py

def alt_of(name):
    return re.search(r'aria-label="([^"]+)"', (OUT.parent / 'assets' / f'{name}.svg').read_text()).group(1)

def src(name):
    """asset URL with a content hash, so browsers drop their cached copy as soon as the file changes"""
    return f'assets/{name}.svg?v={hashlib.md5((OUT.parent / "assets" / f"{name}.svg").read_bytes()).hexdigest()[:8]}'

def pic(name, width='100%', alt=None, href=None, align=None):
    alt = alt or alt_of(name)
    al = f' align="{align}"' if align else ''
    s = (f'<picture><source media="(prefers-color-scheme: dark)" srcset="{src(name)}"><source media="(prefers-color-scheme: light)" '
         f'srcset="{src(name + "-light")}"><img src="{src(name)}" width="{width}"{al} alt="{alt}"></picture>')
    return f'<a href="{href}">{s}</a>' if href else s

def img(name, width='100%', alt=None, href=None):
    s = f'<img src="{src(name)}" width="{width}" alt="{alt or alt_of(name)}">'
    return f'<a href="{href}">{s}</a>' if href else s

FT = 'https://flavor-tree-frontend.vercel.app'
def fold(n, *body):
    # a chapter the reader opens: its strip is the <summary>, everything else stays shut until clicked
    return ['<details>', f'<summary>{pic(f"chapter-{n}", SUMMARY_W, align="middle")}</summary>', '', *body, '</details>', '']

SUMMARY_W = '96%'   # leaves room for GitHub's disclosure triangle on the same line as the strip
parts = [
'<!-- Akai (赤) Anime profile. Every SVG in assets/ is generated by tools/build_assets.py, tools/lab.py, tools/protagonist.py, tools/dividers.py and tools/katana.py; the contribution log is drawn daily by tools/contrib_turtle.py in GitHub Actions. All type is vector paths, so it renders the same on every OS. This file is written by tools/build_readme.py. -->',
'',
'<p align="center">',
pic('hero'),
pic('ribbon-status'),
'</p>',
'',
pic('protagonist'),
'',
'<br>',
'',
*fold('01',
      pic('arsenal'), '',
      pic('divider-saya'), ''),
*fold('02',
      '<p align="center">', img('ft-page-champ', href=FT), '</p>', '',
      pic('flavor-stats'), '',
      '<p>',
      pic('btn-live', '32.9%', href=FT),
      pic('btn-devrepo', '32.9%', href='https://github.com/overloooooord/efesccl-champ'),
      pic('btn-teamrepo', '32.9%', href='https://github.com/Adelllya/Efes-ccl-Flavor'),
      '</p>', '',
      pic('quest-smm'), '',
      '<p>', pic('quest-invision', '49.5%', href='https://github.com/overloooooord/indrive/tree/3c30480') + pic('quest-igtg', '49.5%'), '</p>', '',
      pic('divider-draw'), ''),
*fold('03',
      pic('workshop'), '',
      '<p align="center">', img('fe-pages', href='https://www.rdrightnow.com'), '</p>', '',
      pic('divider-daisho'), ''),
*fold('04',
      f'<picture><source media="(prefers-color-scheme: dark)" srcset="{LOG}-dark.svg"><source media="(prefers-color-scheme: light)" srcset="{LOG}.svg"><img src="{LOG}-dark.svg" width="100%" alt="Contribution log, updated daily: contributions in the last year, the longest streak, public repositories, and a ninja turtle that walks the calendar and cuts every day with commits"></picture>', ''),
'<br>',
'',
pic('chapter-next'),
'',
'<p>',
img('print', '49.8%') + pic('next-episode', '49.8%'),
'</p>',
'',
'<p>',
pic('btn-telegram', '32.9%', href='https://t.me/dreamdrainer'),
pic('btn-instagram', '32.9%', href='https://www.instagram.com/_abutalifuly_/'),
pic('btn-tiktok', '32.9%', href='https://www.tiktok.com/@machiavellistt'),
'</p>',
'',
pic('footer'),
'',
]
md = '\n'.join(parts) + '\n'
assert not re.search('[—–]', md), 'dash found'
OUT.write_text(md)
print(OUT, len(md), 'chars', md.count('<img'), 'imgs')
